#baseURL = "https://ryancoxcomedy.com/"
baseURL = "http://ryancoxcomedy.com.s3-website-us-east-1.amazonaws.com"
languageCode = "en-us"
paginate = 6
summarylength = 10
title = "Ryan Cox | Stand-Up Comedian"
theme = "blogge"

[params]
  summarylength = 80
  logo = "images/ryan-cox-logo.png"
  author = "ryancoxjokes"
  authorThumb = "images/author.png"
  authorAddress = "Lorem 142 Str., 2352, Ipsum, State, USA"
  authorPhone = "+33-257634 534"
  instaUsername = "ryancoxjokes"
  googleMapAPI = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"

[taxonomies]
  tag = "tags"
