baseURL = "https://ryancoxcomedy.com/"
languageCode = "en-us"
title = "Ryan Cox | Stand-Up Comedian"
theme = "blogge"

[params]
  mainImage = "/images/ryan-cox-idiot-box.jpg"
  author = "ryancoxcomedy"
  instaUsername = "ryancoxcomedy"
